# -*- coding: utf-8 -*-
"""Mini_Curso_Fat2DBC.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fxgAF1DMhGTyrjmrN2FP8mrvil-vZyH0

# **Passo 1: Instalar as Bibliotecas**

**Antes de começar a análise, precisamos instalar os pacotes necessários**
"""

# Instalar bibliotecas
install.packages('ExpDes.pt')  # Pacote para análises estatísticas experimentais
install.packages('readxl')      # Pacote para ler arquivos do Excel

"""**📌 ExpDes.pt: Facilita análises experimentais como ANOVA e Testes de Médias.**

**📌 readxl: Permite a importação de arquivos do Excel para o R.**

# **Passo 2: Importar as Bibliotecas**

**Após a instalação, carregamos as bibliotecas para usá-las no código.**
"""

# Importar Bibliotecas
library('ExpDes.pt')
library('readxl')

"""**📌 library() carrega os pacotes para serem utilizados no ambiente do R.**

# **Passo 3: Importar os Dados**

**Agora, importamos o arquivo Excel que contém os dados do experimento.**
"""

# Importando os dados
dados <- read_excel('/content/mini_curso_fat2_dbc.xlsx')

"""**📌 read_excel() lê arquivos do Excel. O caminho do arquivo deve estar correto.**

**❗ Dica: Se o arquivo estiver no Google Drive, primeiro ele precisa ser carregado para a pasta correta.**

# **Passo 4: Visualizar os Dados**

**É sempre importante verificar os dados antes de realizar análises.**
"""

# Ler os primeiros registros do dataset
head(dados)

"""**📌 head() mostra as primeiras linhas do conjunto de dados.**

# **Passo 5: Resumo Estatístico dos Dados**

**Podemos obter estatísticas descritivas rapidamente com a função summary().**
"""

# Resumo estatístico dos dados
summary(dados)

"""**📌 O summary() fornece informações como:**

**✔ Mínimo, máximo, média e mediana das variáveis numéricas.**

**✔ Frequência de variáveis categóricas.**

# **Passo 6: Analisar a Distribuição da Variável "Altura"**

**Para visualizar a distribuição dos dados, utilizamos um histograma.**
"""

# Avaliar distribuição da variável "altura"
hist(dados$diametro,
     main='Frequência de distribuição de dados',
     xlab='altura',
     col='blue',
     border='black')

"""**📌 O hist() cria um histograma, permitindo verificar a normalidade dos dados.**

# **Passo 7: Boxplot da Variável**

**O boxplot é uma ferramenta útil para visualizar a dispersão dos dados e identificar possíveis outliers.**
"""

# Criar um boxplot para a variável "altura"
boxplot(dados$altura,
        main = "Boxplot da Altura",
        ylab = "Altura (m)", col = "lightblue",
        border = "black")

"""**📌 O boxplot() ajuda a visualizar:**

**✔ A mediana da variável.**

**✔ A dispersão dos dados (quartis).**

**✔ Outliers (valores atípicos que podem influenciar a análise).**

# **Passo 8: ANOVA e Teste de Médias Fatorial em DBC**

**Agora realizamos a análise de variância e o teste de comparação de médias.**
"""

# ANOVA e Teste de Tukey para DIC
fat2.dbc(dados$clones, dados$espacamento, dados$blocos, dados$diametro,
    quali=c(TRUE, TRUE),       # Variável qualitativa (tratamento)
    mcomp = 'tukey',    # Teste de Tukey para comparar médias
    fac.names = c('Clones','Espaçamentos'), # Definir o nome para as variáveis
    sigT = 0.05,        # Nível de significância para o teste de médias
    sigF = 0.05)        # Nível de significância para a ANOVA

"""**📌 O fat2.dbc() realiza a ANOVA e o Teste de Tukey para um Fatorial duplo em Delineamento em Blocos ao Acaso (DBC).**

**📌 O teste de Bartlett verifica se as variâncias entre os grupos são homogêneas (princípio da ANOVA).**

**📌 O Teste de Tukey compara as médias e indica diferenças estatísticas entre os tratamentos.**

**📌 Conclusão**

**Este código cobre desde a importação dos dados até a realização da análise estatística. Ele permite:**

**✔ Explorar os dados e verificar sua distribuição.**

**✔ Aplicar ANOVA para identificar diferenças entre os tratamentos.**

**✔ Utilizar o Teste de Tukey para determinar quais grupos diferem significativamente.**

**Agora, podemos interpretar os resultados e visualizar as diferenças entre os tratamentos! 🚀**
"""